#!/usr/bin/env python3
"""Generate design-system components from a selected theme."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


GENERATED_HEADER = "Generated by design-architect. Do not edit manually."
SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
THEMES_ROOT = SKILL_ROOT / "themes"
RICH_THEME_SECTIONS = ("colors", "typography", "spacing", "radii", "borders", "shadows", "motion", "components")


HEX_COLOR_FIELDS = [
    "page",
    "surface",
    "secondarySurface",
    "header",
    "headerBorder",
    "footer",
    "primaryText",
    "secondaryText",
    "placeholderText",
    "border",
    "focusRing",
    "brand",
    "hover",
    "primaryButton",
    "primaryButtonText",
    "secondaryButton",
    "secondaryButtonText",
    "selectedButton",
    "selectedButtonText",
    "danger",
    "dangerSoft",
    "dangerText",
    "success",
    "successSoft",
    "warning",
    "warningSoft",
    "info",
    "infoSoft",
]

BORDER_SCALES = ("none", "small", "medium", "large")
BORDER_WIDTHS = {
    "none": "0",
    "small": "1",
    "medium": "2",
    "large": "3",
}
BORDER_RADII = {
    "none": "0",
    "small": "8",
    "medium": "16",
    "large": "24",
}


@dataclass(frozen=True)
class ThemeTokens:
    slug: str
    name: str
    description: str
    font_family: str
    page: str
    surface: str
    secondary_surface: str
    header: str
    header_border: str
    footer: str
    primary_text: str
    secondary_text: str
    placeholder_text: str
    border: str
    focus_ring: str
    brand: str
    hover: str
    primary_button: str
    primary_button_text: str
    secondary_button: str
    secondary_button_text: str
    selected_button: str
    selected_button_text: str
    danger: str
    danger_soft: str
    danger_text: str
    success: str
    success_soft: str
    warning: str
    warning_soft: str
    info: str
    info_soft: str
    box_width: str
    label_width: str
    button_width: str
    box_radius: int
    label_radius: int
    button_radius: int
    typography_tokens: dict[str, object] = field(default_factory=dict)
    color_tokens: dict[str, object] = field(default_factory=dict)
    spacing_tokens: dict[str, object] = field(default_factory=dict)
    radii_tokens: dict[str, object] = field(default_factory=dict)
    border_tokens: dict[str, object] = field(default_factory=dict)
    shadow_tokens: dict[str, object] = field(default_factory=dict)
    motion_tokens: dict[str, object] = field(default_factory=dict)
    component_tokens: dict[str, object] = field(default_factory=dict)


def available_themes() -> list[str]:
    if not THEMES_ROOT.exists():
        return []
    ignored = {"theme.schema", "SPEC"}
    return sorted(path.stem for path in THEMES_ROOT.glob("*.json") if path.stem not in ignored)


def read_theme(slug: str) -> ThemeTokens:
    theme_path = THEMES_ROOT / f"{slug}.json"
    if not theme_path.is_file():
        choices = ", ".join(available_themes()) or "none"
        raise ValueError(f"Unknown theme '{slug}'. Available themes: {choices}.")

    try:
        data = json.loads(theme_path.read_text())
    except json.JSONDecodeError as error:
        raise ValueError(f"{theme_path} is not valid JSON: {error}") from error

    if is_rich_theme_json(data):
        validate_rich_theme_json(data, theme_path, expected_slug=slug)
        return rich_theme_tokens(data)

    validate_theme_json(data, theme_path, expected_slug=slug)
    return legacy_theme_tokens(data)


def legacy_theme_tokens(data: dict[str, object]) -> ThemeTokens:
    colors = data["colors"]
    typography = data["typography"]
    components = data["components"]

    button_width = css_width(components["buttonBorders"])
    box_width = css_width(components["boxBorders"])
    label_width = css_width(components["labelBorders"])
    button_radius = int(BORDER_RADII[components["buttonBorders"]])
    box_radius = int(BORDER_RADII[components["boxBorders"]])
    label_radius = int(BORDER_RADII[components["labelBorders"]])

    return ThemeTokens(
        slug=data["id"],
        name=data["name"],
        description=data["description"],
        font_family=typography["fontFamily"],
        page=colors["page"],
        surface=colors["surface"],
        secondary_surface=colors["secondarySurface"],
        header=colors["header"],
        header_border=colors["headerBorder"],
        footer=colors["footer"],
        primary_text=colors["primaryText"],
        secondary_text=colors["secondaryText"],
        placeholder_text=colors["placeholderText"],
        border=colors["border"],
        focus_ring=colors["focusRing"],
        brand=colors["brand"],
        hover=colors["hover"],
        primary_button=colors["primaryButton"],
        primary_button_text=colors["primaryButtonText"],
        secondary_button=colors["secondaryButton"],
        secondary_button_text=colors["secondaryButtonText"],
        selected_button=colors["selectedButton"],
        selected_button_text=colors["selectedButtonText"],
        danger=colors["danger"],
        danger_soft=colors["dangerSoft"],
        danger_text=colors["dangerText"],
        success=colors["success"],
        success_soft=colors["successSoft"],
        warning=colors["warning"],
        warning_soft=colors["warningSoft"],
        info=colors["info"],
        info_soft=colors["infoSoft"],
        box_width=box_width,
        label_width=label_width,
        button_width=button_width,
        box_radius=box_radius,
        label_radius=label_radius,
        button_radius=button_radius,
        typography_tokens={
            "product": {
                "family": typography["fontFamily"],
                "bodyWeight": typography["bodyWeight"],
                "boldWeight": typography["headingWeight"],
                "lineHeight": typography["lineHeight"],
            },
            "scale": {},
        },
        color_tokens=colors,
        spacing_tokens={"base": 4, "scale": [4, 8, 12, 16, 20, 24, 32, 40, 48, 64]},
        radii_tokens={
            "button": button_radius,
            "input": button_radius,
            "badge": label_radius,
            "card": box_radius,
        },
        border_tokens={
            "defaultWidth": points_width(button_width),
            "boxWidth": box_width,
            "labelWidth": label_width,
            "buttonWidth": button_width,
        },
        shadow_tokens={"card": "none", "button": "none", "popover": "none", "modal": "none", "drawer": "none"},
        motion_tokens={"hover": "120ms ease", "base": "200ms ease", "modal": "320ms ease"},
        component_tokens={
            "button": {
                "sizes": {"lg": {"height": 40, "paddingX": 12, "fontSize": 14}},
                "variants": ["primary", "secondary", "dangerPrimary", "dangerSecondary"],
                "states": ["default", "hover", "active", "focusVisible", "disabled"],
            },
            "input": {"height": 40, "radius": button_radius, "paddingX": 12},
            "badge": {"paddingY": 3, "paddingX": 10, "radius": label_radius, "fontSize": 12},
            "card": {"surface": "colors.surface", "border": "colors.border", "radius": box_radius, "shadow": "none", "padding": [24]},
        },
    )


def rich_theme_tokens(data: dict[str, object]) -> ThemeTokens:
    rich_payload = {section: data[section] for section in RICH_THEME_SECTIONS}
    audit_rich_theme_payload(data, rich_payload)
    colors = data["colors"]
    brand = colors["brand"]
    background = colors["background"]
    foreground = colors["foreground"]
    border = colors["border"]
    button = colors["button"]
    semantic = colors["semantic"]
    typography = data["typography"]
    product_type = typography["product"]
    radii = data["radii"]
    borders = data["borders"]
    default_width = css_number_width(borders["defaultWidth"])

    return ThemeTokens(
        slug=data["id"],
        name=data["name"],
        description=data["description"],
        font_family=product_type["family"],
        page=background["canvas"],
        surface=background["surface"],
        secondary_surface=background["search"],
        header=background["page"],
        header_border=border["subtle"],
        footer=background["page"],
        primary_text=foreground["primary"],
        secondary_text=foreground["secondary"],
        placeholder_text=foreground["tertiary"],
        border=border["default"],
        focus_ring=brand["ring"],
        brand=brand["default"],
        hover=background["surfaceHover"],
        primary_button=button["primaryBg"],
        primary_button_text=button["primaryText"],
        secondary_button=button["secondaryBg"],
        secondary_button_text=button["secondaryText"],
        selected_button=background["surfaceSelected"],
        selected_button_text=brand["hover"],
        danger=semantic["danger"]["buttonBg"],
        danger_soft=semantic["danger"]["bg"],
        danger_text=semantic["danger"]["fg"],
        success=semantic["success"]["fg"],
        success_soft=semantic["success"]["bg"],
        warning=semantic["warning"]["fg"],
        warning_soft=semantic["warning"]["bg"],
        info=semantic["info"]["fg"],
        info_soft=semantic["info"]["bg"],
        box_width=default_width,
        label_width=default_width,
        button_width=default_width,
        box_radius=int(radii["card"]),
        label_radius=int(radii["badge"]),
        button_radius=int(radii["button"]),
        typography_tokens=rich_payload["typography"],
        color_tokens=rich_payload["colors"],
        spacing_tokens=rich_payload["spacing"],
        radii_tokens=rich_payload["radii"],
        border_tokens=rich_payload["borders"],
        shadow_tokens=rich_payload["shadows"],
        motion_tokens=rich_payload["motion"],
        component_tokens=rich_payload["components"],
    )


def audit_rich_theme_payload(data: dict[str, object], payload: dict[str, object]) -> None:
    source_paths = set(leaf_paths({section: data[section] for section in RICH_THEME_SECTIONS}))
    emitted_paths = set(leaf_paths(payload))
    missing_paths = sorted(source_paths - emitted_paths)
    if missing_paths:
        preview = ", ".join(missing_paths[:8])
        raise ValueError(f"Rich theme payload is missing schema values: {preview}.")


def leaf_paths(value: object, prefix: str = "") -> list[str]:
    if isinstance(value, dict):
        paths: list[str] = []
        for key, child in value.items():
            child_prefix = f"{prefix}.{key}" if prefix else str(key)
            paths.extend(leaf_paths(child, child_prefix))
        return paths
    if isinstance(value, list):
        paths: list[str] = []
        for index, child in enumerate(value):
            paths.extend(leaf_paths(child, f"{prefix}[{index}]"))
        return paths or [prefix]
    return [prefix]


def validate_theme_json(data: object, path: Path, expected_slug: str | None = None) -> None:
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object.")

    required_top = ("id", "name", "description", "typography", "colors", "components")
    require_keys(data, required_top, path)

    if expected_slug is not None and data["id"] != expected_slug:
        raise ValueError(f"{path} id must match its directory name '{expected_slug}'.")

    for key in ("id", "name", "description"):
        if not isinstance(data[key], str) or not data[key].strip():
            raise ValueError(f"{path} field '{key}' must be a non-empty string.")

    typography = require_object(data, "typography", path)
    require_keys(typography, ("fontFamily", "headingWeight", "bodyWeight", "lineHeight"), path / "typography")
    if not isinstance(typography["fontFamily"], str) or not typography["fontFamily"].strip():
        raise ValueError(f"{path} typography.fontFamily must be a non-empty string.")
    for key in ("headingWeight", "bodyWeight"):
        if not isinstance(typography[key], int):
            raise ValueError(f"{path} typography.{key} must be an integer.")
    if not isinstance(typography["lineHeight"], (int, float)):
        raise ValueError(f"{path} typography.lineHeight must be a number.")

    colors = require_object(data, "colors", path)
    require_keys(colors, HEX_COLOR_FIELDS, path / "colors")
    for key in HEX_COLOR_FIELDS:
        if not is_hex_color(colors[key]):
            raise ValueError(f"{path} colors.{key} must be a #RRGGBB or #RRGGBBAA color.")

    components = require_object(data, "components", path)
    require_keys(components, ("boxBorders", "labelBorders", "buttonBorders"), path / "components")
    for key in ("boxBorders", "labelBorders", "buttonBorders"):
        if components[key] not in BORDER_SCALES:
            raise ValueError(f"{path} components.{key} must be one of: {', '.join(BORDER_SCALES)}.")


def is_rich_theme_json(data: object) -> bool:
    return isinstance(data, dict) and isinstance(data.get("spacing"), dict) and isinstance(data.get("radii"), dict)


def validate_rich_theme_json(data: object, path: Path, expected_slug: str | None = None) -> None:
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object.")

    require_keys(
        data,
        (
            "id",
            "name",
            "description",
            "colors",
            "typography",
            "spacing",
            "radii",
            "borders",
            "shadows",
            "motion",
            "components",
        ),
        path,
    )

    if expected_slug is not None and data["id"] != expected_slug:
        raise ValueError(f"{path} id must match its directory name '{expected_slug}'.")

    for key in ("id", "name", "description"):
        if not isinstance(data[key], str) or not data[key].strip():
            raise ValueError(f"{path} field '{key}' must be a non-empty string.")

    colors = require_object(data, "colors", path)
    for key in ("brand", "background", "foreground", "border", "button", "semantic"):
        require_object(colors, key, path / "colors")

    brand = colors["brand"]
    require_color_keys(brand, ("default", "hover", "ring", "surface", "border"), path / "colors" / "brand")

    background = colors["background"]
    require_color_keys(
        background,
        ("page", "canvas", "surface", "surfaceHover", "surfaceSelected", "surfaceInverse", "search", "searchActive", "searchSelected"),
        path / "colors" / "background",
    )

    foreground = colors["foreground"]
    require_color_keys(
        foreground,
        ("primary", "secondary", "tertiary", "disabled", "inverse", "link", "linkHover"),
        path / "colors" / "foreground",
    )

    border = colors["border"]
    require_keys(border, ("default", "subtle", "hover", "strongHover", "focus", "divider"), path / "colors" / "border")
    for key in ("default", "subtle", "hover", "strongHover", "focus"):
        if not is_hex_color(border[key]):
            raise ValueError(f"{path} colors.border.{key} must be a #RRGGBB or #RRGGBBAA color.")

    button = colors["button"]
    require_color_keys(
        button,
        (
            "primaryBg",
            "primaryText",
            "primaryHoverBg",
            "primaryActiveBg",
            "secondaryBg",
            "secondaryText",
            "secondaryBorder",
            "secondaryHoverBorder",
            "secondaryActiveBg",
            "secondaryActiveBorder",
            "disabledBg",
            "disabledText",
        ),
        path / "colors" / "button",
    )

    semantic = colors["semantic"]
    for key in ("info", "success", "warning"):
        group = require_object(semantic, key, path / "colors" / "semantic")
        require_color_keys(group, ("bg", "fg", "border"), path / "colors" / "semantic" / key)
    danger = require_object(semantic, "danger", path / "colors" / "semantic")
    require_color_keys(danger, ("bg", "fg", "border", "buttonBg", "buttonHoverBg", "buttonActiveBg"), path / "colors" / "semantic" / "danger")

    typography = require_object(data, "typography", path)
    product = require_object(typography, "product", path / "typography")
    require_keys(product, ("family", "bodyWeight", "boldWeight", "lineHeight"), path / "typography" / "product")

    radii = require_object(data, "radii", path)
    for key in ("button", "input", "badge", "card"):
        if not isinstance(radii.get(key), int):
            raise ValueError(f"{path} radii.{key} must be an integer.")

    borders = require_object(data, "borders", path)
    if not isinstance(borders.get("defaultWidth"), int):
        raise ValueError(f"{path} borders.defaultWidth must be an integer.")


def require_color_keys(data: dict[str, object], keys: tuple[str, ...], path: Path) -> None:
    require_keys(data, keys, path)
    for key in keys:
        if not is_hex_color(data[key]):
            raise ValueError(f"{path}.{key} must be a #RRGGBB or #RRGGBBAA color.")


def require_object(data: dict[str, object], key: str, path: Path) -> dict[str, object]:
    value = data[key]
    if not isinstance(value, dict):
        raise ValueError(f"{path} field '{key}' must be an object.")
    return value


def require_keys(data: dict[str, object], keys: tuple[str, ...] | list[str], path: Path) -> None:
    missing = [key for key in keys if key not in data]
    if missing:
        raise ValueError(f"{path} is missing required fields: {', '.join(missing)}.")


def is_hex_color(value: object) -> bool:
    if not isinstance(value, str):
        return False
    raw = value.removeprefix("#")
    return value.startswith("#") and len(raw) in (6, 8) and all(char in "0123456789abcdefABCDEF" for char in raw)


def swift(tokens: ThemeTokens) -> str:
    box_width = points_width(tokens.box_width)
    label_width = points_width(tokens.label_width)
    button_width = points_width(tokens.button_width)
    box_radius = tokens.box_radius
    label_radius = tokens.label_radius
    button_radius = tokens.button_radius
    spacing = spacing_values(tokens)
    scale = raw_group(tokens.typography_tokens, "scale")
    h5 = raw_group(scale, "h5")
    body3 = raw_group(scale, "body3")
    body4 = raw_group(scale, "body4")
    body5 = raw_group(scale, "body5")
    button_component = raw_group(tokens.component_tokens, "button")
    button_sizes = raw_group(button_component, "sizes")
    button_sm = raw_group(button_sizes, "sm")
    button_md = raw_group(button_sizes, "md")
    button_lg = raw_group(button_sizes, "lg")
    input_component = raw_group(tokens.component_tokens, "input")
    badge_component = raw_group(tokens.component_tokens, "badge")
    card_component = raw_group(tokens.component_tokens, "card")
    card_padding = first_int(card_component.get("padding"), spacing["xlarge"])
    input_height = int_value(input_component.get("height"), 40)
    input_padding_x = int_value(input_component.get("paddingX"), 12)
    badge_padding_y = int_value(badge_component.get("paddingY"), 3)
    badge_padding_x = int_value(badge_component.get("paddingX"), 10)
    badge_font_size = int_value(badge_component.get("fontSize"), 12)
    badge_font_weight = int_value(badge_component.get("fontWeight"), 500)
    button_sm_height = int_value(button_sm.get("height"), 30)
    button_md_height = int_value(button_md.get("height"), 32)
    button_lg_height = int_value(button_lg.get("height"), 40)
    button_sm_padding = int_value(button_sm.get("paddingX"), 8)
    button_md_padding = int_value(button_md.get("paddingX"), 12)
    button_lg_padding = int_value(button_lg.get("paddingX"), 12)
    button_sm_font = int_value(button_sm.get("fontSize"), 12)
    button_md_font = int_value(button_md.get("fontSize"), 14)
    button_lg_font = int_value(button_lg.get("fontSize"), 16)
    title_size = int_value(h5.get("size"), 24)
    body_size = int_value(body3.get("size"), 16)
    caption_size = int_value(body4.get("size"), 14)
    subtle_size = int_value(body5.get("size"), 12)
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})
// swiftlint:disable all

import SwiftUI

private extension Color {{
    init(designHex hex: String) {{
        let value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let scanner = Scanner(string: value)
        var rgba: UInt64 = 0
        scanner.scanHexInt64(&rgba)

        let red: Double
        let green: Double
        let blue: Double
        let alpha: Double

        if value.count == 8 {{
            red = Double((rgba >> 24) & 0xff) / 255
            green = Double((rgba >> 16) & 0xff) / 255
            blue = Double((rgba >> 8) & 0xff) / 255
            alpha = Double(rgba & 0xff) / 255
        }} else {{
            red = Double((rgba >> 16) & 0xff) / 255
            green = Double((rgba >> 8) & 0xff) / 255
            blue = Double(rgba & 0xff) / 255
            alpha = 1
        }}

        self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }}
}}

public enum DesignTheme {{
    public static let id = "{tokens.slug}"
    public static let name = "{escape_swift(tokens.name)}"
    public static let description = "{escape_swift(tokens.description)}"
}}

public enum DesignTokens {{
    public enum Color {{
        public static let page = SwiftUI.Color(designHex: "{tokens.page}")
        public static let surface = SwiftUI.Color(designHex: "{tokens.surface}")
        public static let secondarySurface = SwiftUI.Color(designHex: "{tokens.secondary_surface}")
        public static let header = SwiftUI.Color(designHex: "{tokens.header}")
        public static let headerBorder = SwiftUI.Color(designHex: "{tokens.header_border}")
        public static let footer = SwiftUI.Color(designHex: "{tokens.footer}")
        public static let primaryText = SwiftUI.Color(designHex: "{tokens.primary_text}")
        public static let secondaryText = SwiftUI.Color(designHex: "{tokens.secondary_text}")
        public static let placeholderText = SwiftUI.Color(designHex: "{tokens.placeholder_text}")
        public static let border = SwiftUI.Color(designHex: "{tokens.border}")
        public static let focusRing = SwiftUI.Color(designHex: "{tokens.focus_ring}")
        public static let brand = SwiftUI.Color(designHex: "{tokens.brand}")
        public static let hover = SwiftUI.Color(designHex: "{tokens.hover}")
        public static let primaryButton = SwiftUI.Color(designHex: "{tokens.primary_button}")
        public static let primaryButtonText = SwiftUI.Color(designHex: "{tokens.primary_button_text}")
        public static let secondaryButton = SwiftUI.Color(designHex: "{tokens.secondary_button}")
        public static let secondaryButtonText = SwiftUI.Color(designHex: "{tokens.secondary_button_text}")
        public static let selectedButton = SwiftUI.Color(designHex: "{tokens.selected_button}")
        public static let selectedButtonText = SwiftUI.Color(designHex: "{tokens.selected_button_text}")
        public static let danger = SwiftUI.Color(designHex: "{tokens.danger}")
        public static let dangerSoft = SwiftUI.Color(designHex: "{tokens.danger_soft}")
        public static let dangerText = SwiftUI.Color(designHex: "{tokens.danger_text}")
        public static let success = SwiftUI.Color(designHex: "{tokens.success}")
        public static let successSoft = SwiftUI.Color(designHex: "{tokens.success_soft}")
        public static let warning = SwiftUI.Color(designHex: "{tokens.warning}")
        public static let warningSoft = SwiftUI.Color(designHex: "{tokens.warning_soft}")
        public static let info = SwiftUI.Color(designHex: "{tokens.info}")
        public static let infoSoft = SwiftUI.Color(designHex: "{tokens.info_soft}")
    }}

    public enum Typography {{
        public static let family = "{tokens.font_family}"
        public static let heading = Font.custom(family, size: {title_size}).weight(.bold)
        public static let body = Font.custom(family, size: {body_size}).weight(.medium)
        public static let caption = Font.custom(family, size: {caption_size}).weight(.medium)
        public static let subtle = Font.custom(family, size: {subtle_size}).weight(.medium)
        public static let button = Font.custom(family, size: {button_md_font}).weight(.bold)
    }}

    public enum Spacing {{
        public static let xsmall: CGFloat = {spacing["xsmall"]}
        public static let small: CGFloat = {spacing["small"]}
        public static let medium: CGFloat = {spacing["medium"]}
        public static let large: CGFloat = {spacing["large"]}
        public static let xlarge: CGFloat = {spacing["xlarge"]}
    }}

    public enum Radius {{
        public static let button: CGFloat = {button_radius}
        public static let buttonLarge: CGFloat = {button_radius}
        public static let input: CGFloat = {button_radius}
        public static let badge: CGFloat = {label_radius}
        public static let card: CGFloat = {box_radius}
    }}

    public enum Stroke {{
        public static let defaultWidth: CGFloat = {button_width}
        public static let boxWidth: CGFloat = {box_width}
        public static let labelWidth: CGFloat = {label_width}
        public static let buttonWidth: CGFloat = {button_width}
    }}
}}

public enum DesignButtonVariant: Sendable {{
    case primary
    case secondary
    case selected
    case dangerPrimary
    case dangerSecondary
}}

public enum DesignButtonSize: Sendable {{
    case small
    case medium
    case large
}}

public enum DesignBadgeVariant: Sendable {{
    case info
    case neutral
    case success
    case warning
    case danger
}}

public enum DesignTextVariant: Sendable {{
    case title
    case body
    case caption
    case subtle
    case error
}}

public struct DesignButtonStyle: ButtonStyle {{
    private let variant: DesignButtonVariant
    private let size: DesignButtonSize
    private let fillsWidth: Bool

    public init(
        variant: DesignButtonVariant = .primary,
        size: DesignButtonSize = .medium,
        fillsWidth: Bool = false
    ) {{
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
    }}

    public func makeBody(configuration: Configuration) -> some View {{
        configuration.label
            .font(font)
            .lineLimit(1)
            .minimumScaleFactor(0.85)
            .padding(.horizontal, horizontalPadding)
            .frame(minHeight: height)
            .frame(maxWidth: fillsWidth ? .infinity : nil)
            .background(configuration.isPressed ? pressedBackground : background)
            .foregroundStyle(foreground)
            .overlay(
                RoundedRectangle(cornerRadius: cornerRadius)
                    .stroke(borderColor, lineWidth: borderWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
            .contentShape(RoundedRectangle(cornerRadius: cornerRadius))
    }}

    private var font: Font {{
        switch size {{
        case .small: Font.custom(DesignTokens.Typography.family, size: {button_sm_font}).weight(.bold)
        case .medium: Font.custom(DesignTokens.Typography.family, size: {button_md_font}).weight(.bold)
        case .large: Font.custom(DesignTokens.Typography.family, size: {button_lg_font}).weight(.bold)
        }}
    }}

    private var height: CGFloat {{
        switch size {{
        case .small: {button_sm_height}
        case .medium: {button_md_height}
        case .large: {button_lg_height}
        }}
    }}

    private var horizontalPadding: CGFloat {{
        switch size {{
        case .small: {button_sm_padding}
        case .medium: {button_md_padding}
        case .large: {button_lg_padding}
        }}
    }}

    private var cornerRadius: CGFloat {{
        switch size {{
        case .large: DesignTokens.Radius.buttonLarge
        case .medium, .small: DesignTokens.Radius.button
        }}
    }}

    private var background: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButton
        case .secondary: DesignTokens.Color.secondaryButton
        case .selected: DesignTokens.Color.selectedButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var pressedBackground: SwiftUI.Color {{
        switch variant {{
        case .primary, .secondary: DesignTokens.Color.hover
        case .selected: DesignTokens.Color.selectedButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var foreground: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButtonText
        case .secondary: DesignTokens.Color.secondaryButtonText
        case .selected: DesignTokens.Color.selectedButtonText
        case .dangerPrimary: SwiftUI.Color.white
        case .dangerSecondary: DesignTokens.Color.dangerText
        }}
    }}

    private var borderColor: SwiftUI.Color {{
        switch variant {{
        case .primary, .dangerPrimary: SwiftUI.Color.clear
        case .secondary: DesignTokens.Color.border
        case .selected: DesignTokens.Color.selectedButton
        case .dangerSecondary: DesignTokens.Color.danger
        }}
    }}

    private var borderWidth: CGFloat {{
        switch variant {{
        case .primary, .dangerPrimary: 0
        case .secondary, .selected, .dangerSecondary: DesignTokens.Stroke.buttonWidth
        }}
    }}
}}

public struct DesignIconButton: View {{
    private let systemImage: String
    private let accessibilityLabel: String
    private let size: CGFloat
    private let action: () -> Void

    public init(
        systemImage: String,
        accessibilityLabel: String,
        size: CGFloat = 40,
        action: @escaping () -> Void
    ) {{
        self.systemImage = systemImage
        self.accessibilityLabel = accessibilityLabel
        self.size = size
        self.action = action
    }}

    public var body: some View {{
        Button(action: action) {{
            Image(systemName: systemImage)
                .font(.system(size: size * 0.38, weight: .semibold))
                .frame(width: size, height: size)
                .background(DesignTokens.Color.surface)
                .foregroundStyle(DesignTokens.Color.primaryText)
                .overlay(
                    RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge)
                        .stroke(DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.buttonWidth)
                )
                .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge))
        }}
        .buttonStyle(.plain)
        .accessibilityLabel(accessibilityLabel)
    }}
}}

public struct DesignText: View {{
    private let text: String
    private let variant: DesignTextVariant

    public init(_ text: String, variant: DesignTextVariant = .body) {{
        self.text = text
        self.variant = variant
    }}

    public var body: some View {{
        Text(text)
            .font(font)
            .foregroundStyle(color)
            .fixedSize(horizontal: false, vertical: true)
    }}

    private var font: Font {{
        switch variant {{
        case .title: DesignTokens.Typography.heading
        case .body: DesignTokens.Typography.body
        case .caption: DesignTokens.Typography.caption
        case .subtle: DesignTokens.Typography.subtle
        case .error: DesignTokens.Typography.caption
        }}
    }}

    private var color: SwiftUI.Color {{
        switch variant {{
        case .title, .body: DesignTokens.Color.primaryText
        case .caption, .subtle: DesignTokens.Color.secondaryText
        case .error: DesignTokens.Color.danger
        }}
    }}
}}

public struct DesignToggle: View {{
    private let title: String
    @Binding private var isOn: Bool

    public init(_ title: String, isOn: Binding<Bool>) {{
        self.title = title
        self._isOn = isOn
    }}

    public var body: some View {{
        Toggle(title, isOn: $isOn)
            .font(DesignTokens.Typography.caption)
            .foregroundStyle(DesignTokens.Color.primaryText)
            .tint(DesignTokens.Color.brand)
    }}
}}

public struct DesignBadge: View {{
    private let text: String
    private let variant: DesignBadgeVariant

    public init(_ text: String, variant: DesignBadgeVariant = .neutral) {{
        self.text = text
        self.variant = variant
    }}

    public var body: some View {{
        Text(text)
            .font(.custom(DesignTokens.Typography.family, size: {badge_font_size}).weight({swift_font_weight(badge_font_weight)}))
            .foregroundStyle(foregroundColor)
            .padding(.horizontal, {badge_padding_x})
            .padding(.vertical, {badge_padding_y})
            .background(backgroundColor)
            .overlay(
                Capsule()
                    .stroke(borderColor, lineWidth: DesignTokens.Stroke.labelWidth)
            )
            .clipShape(Capsule())
    }}

    private var backgroundColor: SwiftUI.Color {{
        switch variant {{
        case .info: DesignTokens.Color.infoSoft
        case .neutral: DesignTokens.Color.secondarySurface
        case .success: DesignTokens.Color.successSoft
        case .warning: DesignTokens.Color.warningSoft
        case .danger: DesignTokens.Color.dangerSoft
        }}
    }}

    private var foregroundColor: SwiftUI.Color {{
        switch variant {{
        case .info: DesignTokens.Color.info
        case .neutral: DesignTokens.Color.primaryText
        case .success: DesignTokens.Color.success
        case .warning: DesignTokens.Color.warning
        case .danger: DesignTokens.Color.danger
        }}
    }}

    private var borderColor: SwiftUI.Color {{
        switch variant {{
        case .info: DesignTokens.Color.info
        case .neutral: DesignTokens.Color.border
        case .success: DesignTokens.Color.success
        case .warning: DesignTokens.Color.warning
        case .danger: DesignTokens.Color.danger
        }}
    }}
}}

public struct DesignCard<Content: View>: View {{
    private let content: () -> Content

    public init(@ViewBuilder content: @escaping () -> Content) {{
        self.content = content
    }}

    public var body: some View {{
        VStack(alignment: .leading, spacing: DesignTokens.Spacing.large) {{
            content()
        }}
        .padding({card_padding})
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(DesignTokens.Color.surface)
        .overlay(
            RoundedRectangle(cornerRadius: DesignTokens.Radius.card)
                .stroke(DesignTokens.Color.headerBorder, lineWidth: DesignTokens.Stroke.boxWidth)
        )
        .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.card))
    }}
}}

public struct DesignTextField: View {{
    private let title: String
    @Binding private var text: String
    private let isDestructive: Bool

    public init(_ title: String, text: Binding<String>, isDestructive: Bool = false) {{
        self.title = title
        self._text = text
        self.isDestructive = isDestructive
    }}

    public var body: some View {{
        TextField(title, text: $text)
            .font(DesignTokens.Typography.caption)
            .foregroundStyle(DesignTokens.Color.primaryText)
            .padding(.horizontal, {input_padding_x})
            .frame(minHeight: {input_height})
            .background(DesignTokens.Color.secondarySurface)
            .overlay(
                RoundedRectangle(cornerRadius: DesignTokens.Radius.input)
                    .stroke(isDestructive ? DesignTokens.Color.danger : DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.buttonWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.input))
    }}
}}
"""


def kotlin(tokens: ThemeTokens, package_name: str) -> str:
    button_width = dp_width(tokens.button_width)
    button_radius = f"{tokens.button_radius}.dp"
    label_width = dp_width(tokens.label_width)
    box_width = dp_width(tokens.box_width)
    spacing = spacing_values(tokens)
    scale = raw_group(tokens.typography_tokens, "scale")
    h5 = raw_group(scale, "h5")
    body3 = raw_group(scale, "body3")
    body4 = raw_group(scale, "body4")
    body5 = raw_group(scale, "body5")
    button_component = raw_group(tokens.component_tokens, "button")
    button_sizes = raw_group(button_component, "sizes")
    button_sm = raw_group(button_sizes, "sm")
    button_md = raw_group(button_sizes, "md")
    button_lg = raw_group(button_sizes, "lg")
    input_component = raw_group(tokens.component_tokens, "input")
    badge_component = raw_group(tokens.component_tokens, "badge")
    card_component = raw_group(tokens.component_tokens, "card")
    card_padding = first_int(card_component.get("padding"), spacing["xlarge"])
    input_height = int_value(input_component.get("height"), 40)
    input_padding_x = int_value(input_component.get("paddingX"), 12)
    badge_padding_y = int_value(badge_component.get("paddingY"), 3)
    badge_padding_x = int_value(badge_component.get("paddingX"), 10)
    badge_font_size = int_value(badge_component.get("fontSize"), 12)
    badge_font_weight = int_value(badge_component.get("fontWeight"), 500)
    button_sm_height = int_value(button_sm.get("height"), 30)
    button_md_height = int_value(button_md.get("height"), 32)
    button_lg_height = int_value(button_lg.get("height"), 40)
    button_sm_padding = int_value(button_sm.get("paddingX"), 8)
    button_md_padding = int_value(button_md.get("paddingX"), 12)
    button_lg_padding = int_value(button_lg.get("paddingX"), 12)
    button_sm_font = int_value(button_sm.get("fontSize"), 12)
    button_md_font = int_value(button_md.get("fontSize"), 14)
    button_lg_font = int_value(button_lg.get("fontSize"), 16)
    title_size = int_value(h5.get("size"), 24)
    body_size = int_value(body3.get("size"), 16)
    caption_size = int_value(body4.get("size"), 14)
    subtle_size = int_value(body5.get("size"), 12)
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

package {package_name}

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private fun designColor(hex: String): Color {{
    val value = hex.removePrefix("#")
    val rgba = value.toLong(16)
    return if (value.length == 8) {{
        val r = (rgba shr 24) and 0xff
        val g = (rgba shr 16) and 0xff
        val b = (rgba shr 8) and 0xff
        val a = rgba and 0xff
        Color(((a shl 24) or (r shl 16) or (g shl 8) or b).toULong())
    }} else {{
        Color((0xff000000 or rgba).toULong())
    }}
}}

object DesignTheme {{
    const val id = "{tokens.slug}"
    const val name = "{escape_kotlin(tokens.name)}"
    const val description = "{escape_kotlin(tokens.description)}"
}}

object DesignColors {{
    val page = designColor("{tokens.page}")
    val surface = designColor("{tokens.surface}")
    val secondarySurface = designColor("{tokens.secondary_surface}")
    val header = designColor("{tokens.header}")
    val headerBorder = designColor("{tokens.header_border}")
    val footer = designColor("{tokens.footer}")
    val primaryText = designColor("{tokens.primary_text}")
    val secondaryText = designColor("{tokens.secondary_text}")
    val placeholderText = designColor("{tokens.placeholder_text}")
    val border = designColor("{tokens.border}")
    val focusRing = designColor("{tokens.focus_ring}")
    val brand = designColor("{tokens.brand}")
    val hover = designColor("{tokens.hover}")
    val primaryButton = designColor("{tokens.primary_button}")
    val primaryButtonText = designColor("{tokens.primary_button_text}")
    val secondaryButton = designColor("{tokens.secondary_button}")
    val secondaryButtonText = designColor("{tokens.secondary_button_text}")
    val selectedButton = designColor("{tokens.selected_button}")
    val selectedButtonText = designColor("{tokens.selected_button_text}")
    val danger = designColor("{tokens.danger}")
    val dangerSoft = designColor("{tokens.danger_soft}")
    val dangerText = designColor("{tokens.danger_text}")
    val success = designColor("{tokens.success}")
    val successSoft = designColor("{tokens.success_soft}")
    val warning = designColor("{tokens.warning}")
    val warningSoft = designColor("{tokens.warning_soft}")
    val info = designColor("{tokens.info}")
    val infoSoft = designColor("{tokens.info_soft}")
}}

object DesignTypography {{
    val family = FontFamily.Default
    val headingSize = {title_size}.sp
    val bodySize = {body_size}.sp
    val captionSize = {caption_size}.sp
    val subtleSize = {subtle_size}.sp
    val buttonWeight = FontWeight.Bold
    const val preferredFamily = "{tokens.font_family}"
}}

object DesignSpacing {{
    val xsmall = {spacing["xsmall"]}.dp
    val small = {spacing["small"]}.dp
    val medium = {spacing["medium"]}.dp
    val large = {spacing["large"]}.dp
    val xlarge = {spacing["xlarge"]}.dp
}}

object DesignRadii {{
    val button = {tokens.button_radius}.dp
    val buttonLarge = {tokens.button_radius}.dp
    val input = {tokens.button_radius}.dp
    val badge = {tokens.label_radius}.dp
    val card = {tokens.box_radius}.dp
}}

object DesignStrokes {{
    val defaultWidth = {button_width}
    val boxWidth = {box_width}
    val labelWidth = {label_width}
    val buttonWidth = {button_width}
}}

enum class DesignButtonVariant {{
    Primary,
    Secondary,
    Selected,
    DangerPrimary,
    DangerSecondary
}}

enum class DesignButtonSize {{
    Small,
    Medium,
    Large
}}

enum class DesignBadgeVariant {{
    Info,
    Neutral,
    Success,
    Warning,
    Danger
}}

enum class DesignTextVariant {{
    Title,
    Body,
    Caption,
    Subtle,
    Error
}}

@Composable
fun DesignButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    variant: DesignButtonVariant = DesignButtonVariant.Primary,
    size: DesignButtonSize = DesignButtonSize.Medium,
    fillsWidth: Boolean = false,
    enabled: Boolean = true,
) {{
    val container = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButton
        DesignButtonVariant.Secondary -> DesignColors.secondaryButton
        DesignButtonVariant.Selected -> DesignColors.selectedButton
        DesignButtonVariant.DangerPrimary -> DesignColors.danger
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerSoft
    }}
    val content = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButtonText
        DesignButtonVariant.Secondary -> DesignColors.secondaryButtonText
        DesignButtonVariant.Selected -> DesignColors.selectedButtonText
        DesignButtonVariant.DangerPrimary -> Color.White
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerText
    }}
    val minHeight = when (size) {{
        DesignButtonSize.Small -> {button_sm_height}.dp
        DesignButtonSize.Medium -> {button_md_height}.dp
        DesignButtonSize.Large -> {button_lg_height}.dp
    }}
    val horizontalPadding = when (size) {{
        DesignButtonSize.Small -> {button_sm_padding}.dp
        DesignButtonSize.Medium -> {button_md_padding}.dp
        DesignButtonSize.Large -> {button_lg_padding}.dp
    }}
    val fontSize = when (size) {{
        DesignButtonSize.Small -> {button_sm_font}.sp
        DesignButtonSize.Medium -> {button_md_font}.sp
        DesignButtonSize.Large -> {button_lg_font}.sp
    }}
    val buttonModifier = if (fillsWidth) modifier.fillMaxWidth() else modifier
    val border = when (variant) {{
        DesignButtonVariant.Primary,
        DesignButtonVariant.DangerPrimary -> null
        DesignButtonVariant.Secondary,
        DesignButtonVariant.Selected,
        DesignButtonVariant.DangerSecondary -> BorderStroke(DesignStrokes.buttonWidth, DesignColors.border)
    }}

    Button(
        onClick = onClick,
        modifier = buttonModifier.heightIn(min = minHeight),
        enabled = enabled,
        shape = RoundedCornerShape({button_radius}),
        border = border,
        colors = ButtonDefaults.buttonColors(containerColor = container, contentColor = content),
        contentPadding = PaddingValues(horizontal = horizontalPadding, vertical = 0.dp),
    ) {{
        Text(text = text, fontWeight = DesignTypography.buttonWeight, fontSize = fontSize)
    }}
}}

@Composable
fun DesignIconButton(
    imageVector: ImageVector,
    contentDescription: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
) {{
    IconButton(onClick = onClick, modifier = modifier, enabled = enabled) {{
        Icon(imageVector = imageVector, contentDescription = contentDescription, tint = DesignColors.primaryText)
    }}
}}

@Composable
fun DesignText(
    text: String,
    modifier: Modifier = Modifier,
    variant: DesignTextVariant = DesignTextVariant.Body,
) {{
    val fontSize = when (variant) {{
        DesignTextVariant.Title -> DesignTypography.headingSize
        DesignTextVariant.Body -> DesignTypography.bodySize
        DesignTextVariant.Caption -> DesignTypography.captionSize
        DesignTextVariant.Subtle -> DesignTypography.subtleSize
        DesignTextVariant.Error -> DesignTypography.captionSize
    }}
    val color = when (variant) {{
        DesignTextVariant.Title,
        DesignTextVariant.Body -> DesignColors.primaryText
        DesignTextVariant.Caption,
        DesignTextVariant.Subtle -> DesignColors.secondaryText
        DesignTextVariant.Error -> DesignColors.danger
    }}
    Text(text = text, modifier = modifier, color = color, fontSize = fontSize, fontWeight = FontWeight.Medium)
}}

@Composable
fun DesignSwitch(
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
) {{
    Switch(checked = checked, onCheckedChange = onCheckedChange, modifier = modifier, enabled = enabled)
}}

@Composable
fun DesignBadge(
    text: String,
    modifier: Modifier = Modifier,
    variant: DesignBadgeVariant = DesignBadgeVariant.Neutral,
) {{
    val background = when (variant) {{
        DesignBadgeVariant.Info -> DesignColors.infoSoft
        DesignBadgeVariant.Neutral -> DesignColors.secondarySurface
        DesignBadgeVariant.Success -> DesignColors.successSoft
        DesignBadgeVariant.Warning -> DesignColors.warningSoft
        DesignBadgeVariant.Danger -> DesignColors.dangerSoft
    }}
    val content = when (variant) {{
        DesignBadgeVariant.Info -> DesignColors.info
        DesignBadgeVariant.Neutral -> DesignColors.primaryText
        DesignBadgeVariant.Success -> DesignColors.success
        DesignBadgeVariant.Warning -> DesignColors.warning
        DesignBadgeVariant.Danger -> DesignColors.danger
    }}
    Text(
        text = text,
        modifier = modifier
            .background(background, RoundedCornerShape(DesignRadii.badge))
            .border(DesignStrokes.labelWidth, DesignColors.border, RoundedCornerShape(DesignRadii.badge))
            .padding(horizontal = {badge_padding_x}.dp, vertical = {badge_padding_y}.dp),
        color = content,
        fontSize = {badge_font_size}.sp,
        fontWeight = {kotlin_font_weight(badge_font_weight)},
    )
}}

@Composable
fun DesignCard(
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit,
) {{
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(DesignRadii.card),
        border = BorderStroke(DesignStrokes.boxWidth, DesignColors.headerBorder),
        colors = CardDefaults.cardColors(containerColor = DesignColors.surface),
    ) {{
        androidx.compose.foundation.layout.Column(modifier = Modifier.padding({card_padding}.dp)) {{
            content()
        }}
    }}
}}

@Composable
fun DesignTextField(
    value: String,
    onValueChange: (String) -> Unit,
    label: String,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    isError: Boolean = false,
) {{
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = modifier.heightIn(min = {input_height}.dp),
        enabled = enabled,
        isError = isError,
        label = {{ Text(label) }},
        shape = RoundedCornerShape(DesignRadii.input),
    )
}}
"""


def raw_group(data: object, key: str) -> dict[str, object]:
    if isinstance(data, dict) and isinstance(data.get(key), dict):
        return data[key]
    return {}


def int_value(value: object, fallback: int) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return fallback


def first_int(value: object, fallback: int) -> int:
    if isinstance(value, list) and value:
        return int_value(value[0], fallback)
    return int_value(value, fallback)


def str_value(value: object, fallback: str = "") -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (int, float)):
        return f"{value:g}"
    return fallback


def typography_heading_weight(tokens: ThemeTokens) -> int:
    product = raw_group(tokens.typography_tokens, "product")
    return int_value(product.get("boldWeight"), 700)


def typography_body_weight(tokens: ThemeTokens) -> int:
    product = raw_group(tokens.typography_tokens, "product")
    return int_value(product.get("bodyWeight"), 500)


def typography_line_height(tokens: ThemeTokens) -> str:
    product = raw_group(tokens.typography_tokens, "product")
    value = product.get("lineHeight")
    if isinstance(value, (int, float)):
        return f"{value:g}"
    return "1.2"


def ts_literal(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True)


def indent_ts(value: str, spaces: int) -> str:
    lines = value.splitlines()
    if len(lines) <= 1:
        return value
    padding = " " * spaces
    return lines[0] + "\n" + "\n".join(padding + line for line in lines[1:])


def resolve_design_ref(value: object, tokens: ThemeTokens, fallback: str) -> str:
    if not isinstance(value, str):
        return fallback
    resolved = resolve_ref_path(value, tokens)
    if isinstance(resolved, str):
        return resolved
    return value


def resolve_design_style(value: object, tokens: ThemeTokens, fallback: str) -> str:
    if not isinstance(value, str):
        return fallback

    def replace(match: re.Match[str]) -> str:
        resolved = resolve_ref_path(match.group(0), tokens)
        return resolved if isinstance(resolved, str) else match.group(0)

    return re.sub(r"\b[a-zA-Z][a-zA-Z0-9]*\.[a-zA-Z][a-zA-Z0-9]*\b", replace, value)


def resolve_ref_path(path: str, tokens: ThemeTokens) -> object:
    if "." not in path:
        return None
    head, *parts = path.split(".")
    roots: dict[str, object] = {
        "background": raw_group(tokens.color_tokens, "background"),
        "foreground": raw_group(tokens.color_tokens, "foreground"),
        "border": raw_group(tokens.color_tokens, "border"),
        "brand": raw_group(tokens.color_tokens, "brand"),
        "button": raw_group(tokens.color_tokens, "button"),
        "semantic": raw_group(tokens.color_tokens, "semantic"),
        "colors": tokens.color_tokens,
        "radii": tokens.radii_tokens,
        "shadows": tokens.shadow_tokens,
        "motion": tokens.motion_tokens,
    }
    current = roots.get(head)
    for part in parts:
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def component_border_style(tokens: ThemeTokens, key: str, fallback: str) -> str:
    component_borders = raw_group(tokens.border_tokens, "componentBorders")
    return resolve_design_style(component_borders.get(key), tokens, fallback)


def spacing_values(tokens: ThemeTokens) -> dict[str, int]:
    scale = tokens.spacing_tokens.get("scale")
    values = scale if isinstance(scale, list) else []
    return {
        "xsmall": int_value(values[0] if len(values) > 0 else None, 4),
        "small": int_value(values[1] if len(values) > 1 else None, 8),
        "medium": int_value(values[2] if len(values) > 2 else None, 12),
        "large": int_value(values[3] if len(values) > 3 else None, 16),
        "xlarge": int_value(values[5] if len(values) > 5 else None, 24),
    }


def swift_font_weight(weight: int) -> str:
    if weight >= 700:
        return ".bold"
    if weight >= 600:
        return ".semibold"
    if weight >= 500:
        return ".medium"
    return ".regular"


def kotlin_font_weight(weight: int) -> str:
    if weight >= 700:
        return "FontWeight.Bold"
    if weight >= 600:
        return "FontWeight.SemiBold"
    if weight >= 500:
        return "FontWeight.Medium"
    return "FontWeight.Normal"


def typescript(tokens: ThemeTokens) -> str:
    box_width = tokens.box_width
    label_width = tokens.label_width
    button_width = tokens.button_width
    box_radius = tokens.box_radius
    label_radius = tokens.label_radius
    button_radius = tokens.button_radius
    button_colors = raw_group(tokens.color_tokens, "button")
    semantic_colors = raw_group(tokens.color_tokens, "semantic")
    danger_colors = raw_group(semantic_colors, "danger")
    button_component = raw_group(tokens.component_tokens, "button")
    input_component = raw_group(tokens.component_tokens, "input")
    badge_component = raw_group(tokens.component_tokens, "badge")
    card_component = raw_group(tokens.component_tokens, "card")
    table_component = raw_group(tokens.component_tokens, "table")
    modal_component = raw_group(tokens.component_tokens, "modal")
    drawer_component = raw_group(tokens.component_tokens, "drawer")
    toast_component = raw_group(tokens.component_tokens, "toast")
    app_shell_component = raw_group(tokens.component_tokens, "appShell")
    button_sizes = raw_group(button_component, "sizes")
    button_lg = raw_group(button_sizes, "lg")
    input_height = int_value(input_component.get("height"), 40)
    input_active_height = int_value(input_component.get("activeHeight"), input_height)
    input_padding_x = int_value(input_component.get("paddingX"), 12)
    badge_padding_y = int_value(badge_component.get("paddingY"), 3)
    badge_padding_x = int_value(badge_component.get("paddingX"), 10)
    badge_font_size = int_value(badge_component.get("fontSize"), 12)
    badge_font_weight = int_value(badge_component.get("fontWeight"), 500)
    card_padding = first_int(card_component.get("padding"), 24)
    card_shadow = str_value(card_component.get("shadow"), "none")
    table_header_size = int_value(table_component.get("headerSize"), 12)
    table_cell_padding_y = int_value(table_component.get("cellPaddingY"), 12)
    table_cell_padding_x = int_value(table_component.get("cellPaddingX"), 18)
    modal_width = int_value(modal_component.get("desktopWidth"), 400)
    toast_padding_y = int_value(toast_component.get("paddingY"), 16)
    toast_padding_x = int_value(toast_component.get("paddingX"), 20)
    primary_hover = str_value(button_colors.get("primaryHoverBg"), tokens.hover)
    primary_active = str_value(button_colors.get("primaryActiveBg"), primary_hover)
    secondary_border = str_value(button_colors.get("secondaryBorder"), tokens.border)
    secondary_hover_border = str_value(button_colors.get("secondaryHoverBorder"), secondary_border)
    secondary_active_bg = str_value(button_colors.get("secondaryActiveBg"), tokens.hover)
    secondary_active_border = str_value(button_colors.get("secondaryActiveBorder"), secondary_hover_border)
    disabled_bg = str_value(button_colors.get("disabledBg"), tokens.secondary_surface)
    disabled_text = str_value(button_colors.get("disabledText"), tokens.placeholder_text)
    danger_hover = str_value(danger_colors.get("buttonHoverBg"), tokens.danger)
    danger_active = str_value(danger_colors.get("buttonActiveBg"), tokens.danger)
    focus_width = css_number_width(tokens.border_tokens.get("focusRingWidth", 2))
    card_surface = resolve_design_ref(card_component.get("surface"), tokens, tokens.surface)
    card_border_style = component_border_style(tokens, "card", f"{tokens.box_width} solid {tokens.border}")
    input_border_style = component_border_style(tokens, "input", f"{tokens.button_width} solid {tokens.border}")
    table_row_border_style = component_border_style(tokens, "tableRow", f"{tokens.box_width} solid {tokens.header_border}")
    table_header_bg = resolve_design_ref(table_component.get("headerBg"), tokens, tokens.secondary_surface)
    table_row_hover_bg = resolve_design_ref(table_component.get("rowHoverBg"), tokens, tokens.hover)
    sidebar_bg = resolve_design_ref(app_shell_component.get("sidebarBg"), tokens, tokens.surface)
    main_bg = resolve_design_ref(app_shell_component.get("mainBg"), tokens, tokens.page)
    active_nav_bg = resolve_design_ref(app_shell_component.get("activeNavBg"), tokens, tokens.selected_button)
    active_nav_text = resolve_design_ref(app_shell_component.get("activeNavText"), tokens, tokens.selected_button_text)
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

export const designTheme = {{
  id: "{tokens.slug}",
  name: "{escape_ts(tokens.name)}",
  description: "{escape_ts(tokens.description)}",
}} as const;

export const designTokens = {{
  colors: {{
    page: "{tokens.page}",
    surface: "{tokens.surface}",
    secondarySurface: "{tokens.secondary_surface}",
    header: "{tokens.header}",
    headerBorder: "{tokens.header_border}",
    footer: "{tokens.footer}",
    primaryText: "{tokens.primary_text}",
    secondaryText: "{tokens.secondary_text}",
    placeholderText: "{tokens.placeholder_text}",
    border: "{tokens.border}",
    focusRing: "{tokens.focus_ring}",
    brand: "{tokens.brand}",
    hover: "{tokens.hover}",
    primaryButton: "{tokens.primary_button}",
    primaryButtonText: "{tokens.primary_button_text}",
    secondaryButton: "{tokens.secondary_button}",
    secondaryButtonText: "{tokens.secondary_button_text}",
    selectedButton: "{tokens.selected_button}",
    selectedButtonText: "{tokens.selected_button_text}",
    danger: "{tokens.danger}",
    dangerSoft: "{tokens.danger_soft}",
    dangerText: "{tokens.danger_text}",
    success: "{tokens.success}",
    successSoft: "{tokens.success_soft}",
    warning: "{tokens.warning}",
    warningSoft: "{tokens.warning_soft}",
    info: "{tokens.info}",
    infoSoft: "{tokens.info_soft}",
  }},
  rawColors: {indent_ts(ts_literal(tokens.color_tokens), 2)},
  typography: {{
    fontFamily: "{tokens.font_family}",
    headingWeight: {typography_heading_weight(tokens)},
    bodyWeight: {typography_body_weight(tokens)},
    lineHeight: {typography_line_height(tokens)},
    raw: {indent_ts(ts_literal(tokens.typography_tokens), 4)},
  }},
  spacing: {indent_ts(ts_literal(tokens.spacing_tokens), 2)},
  radii: {{
    button: {button_radius},
    buttonLarge: {button_radius},
    input: {button_radius},
    badge: {label_radius},
    card: {box_radius},
    raw: {indent_ts(ts_literal(tokens.radii_tokens), 4)},
  }},
  borders: {{
    defaultWidth: "{button_width}",
    boxWidth: "{box_width}",
    labelWidth: "{label_width}",
    buttonWidth: "{button_width}",
    focusRingWidth: "{focus_width}",
    raw: {indent_ts(ts_literal(tokens.border_tokens), 4)},
  }},
  shadows: {indent_ts(ts_literal(tokens.shadow_tokens), 2)},
  motion: {{
    hover: "{escape_ts(str_value(tokens.motion_tokens.get("hover"), "120ms ease"))}",
    base: "{escape_ts(str_value(tokens.motion_tokens.get("base"), "200ms ease"))}",
    modal: "{escape_ts(str_value(tokens.motion_tokens.get("modal"), "320ms ease"))}",
    raw: {indent_ts(ts_literal(tokens.motion_tokens), 4)},
  }},
  components: {indent_ts(ts_literal(tokens.component_tokens), 2)},
}} as const;

export type DesignButtonVariant = "primary" | "secondary" | "selected" | "dangerPrimary" | "dangerSecondary";
export type DesignBadgeVariant = "info" | "neutral" | "success" | "warning" | "danger";
export type StyleRecipe = Record<string, string | number>;

export const buttonRecipe: Record<DesignButtonVariant, StyleRecipe> = {{
  primary: {{
    background: designTokens.colors.primaryButton,
    color: designTokens.colors.primaryButtonText,
    border: `${{designTokens.borders.buttonWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.button,
    minHeight: {int_value(button_lg.get("height"), 40)},
    paddingInline: {int_value(button_lg.get("paddingX"), 12)},
    fontSize: {int_value(button_lg.get("fontSize"), 14)},
    hoverBackground: "{primary_hover}",
    activeBackground: "{primary_active}",
    disabledBackground: "{disabled_bg}",
    disabledColor: "{disabled_text}",
    transition: designTokens.motion.hover,
  }},
  secondary: {{
    background: designTokens.colors.secondaryButton,
    color: designTokens.colors.secondaryButtonText,
    border: `${{designTokens.borders.buttonWidth}} solid {secondary_border}`,
    borderRadius: designTokens.radii.button,
    minHeight: {int_value(button_lg.get("height"), 40)},
    paddingInline: {int_value(button_lg.get("paddingX"), 12)},
    fontSize: {int_value(button_lg.get("fontSize"), 14)},
    hoverBorderColor: "{secondary_hover_border}",
    activeBackground: "{secondary_active_bg}",
    activeBorderColor: "{secondary_active_border}",
    disabledBackground: "{disabled_bg}",
    disabledColor: "{disabled_text}",
    transition: designTokens.motion.hover,
  }},
  selected: {{
    background: designTokens.colors.selectedButton,
    color: designTokens.colors.selectedButtonText,
    border: `${{designTokens.borders.buttonWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.button,
    minHeight: {int_value(button_lg.get("height"), 40)},
    paddingInline: {int_value(button_lg.get("paddingX"), 12)},
    fontSize: {int_value(button_lg.get("fontSize"), 14)},
  }},
  dangerPrimary: {{
    background: designTokens.colors.danger,
    color: "#FFFFFF",
    border: `${{designTokens.borders.buttonWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.button,
    minHeight: {int_value(button_lg.get("height"), 40)},
    paddingInline: {int_value(button_lg.get("paddingX"), 12)},
    fontSize: {int_value(button_lg.get("fontSize"), 14)},
    hoverBackground: "{danger_hover}",
    activeBackground: "{danger_active}",
    transition: designTokens.motion.hover,
  }},
  dangerSecondary: {{
    background: designTokens.colors.dangerSoft,
    color: designTokens.colors.dangerText,
    border: `${{designTokens.borders.buttonWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.button,
    minHeight: {int_value(button_lg.get("height"), 40)},
    paddingInline: {int_value(button_lg.get("paddingX"), 12)},
    fontSize: {int_value(button_lg.get("fontSize"), 14)},
    hoverBackground: designTokens.colors.hover,
    transition: designTokens.motion.hover,
  }},
}};

export const inputRecipe = {{
  default: {{
    background: designTokens.colors.secondarySurface,
    color: designTokens.colors.primaryText,
    placeholderColor: designTokens.colors.placeholderText,
    border: "{escape_ts(input_border_style)}",
    borderRadius: designTokens.radii.input,
    minHeight: {input_height},
    paddingInline: {input_padding_x},
    transition: designTokens.motion.hover,
  }},
  active: {{
    borderColor: designTokens.colors.focusRing,
    boxShadow: `0 0 0 ${{designTokens.borders.focusRingWidth}} ${{designTokens.colors.focusRing}}`,
    minHeight: {input_active_height},
  }},
  disabled: {{
    background: "{disabled_bg}",
    color: "{disabled_text}",
  }},
  destructive: {{
    borderColor: designTokens.colors.danger,
    color: designTokens.colors.primaryText,
  }},
}} as const;

export const badgeRecipe: Record<DesignBadgeVariant, StyleRecipe> = {{
  info: {{ background: designTokens.colors.infoSoft, color: designTokens.colors.info, border: `${{designTokens.borders.labelWidth}} solid ${{designTokens.colors.border}}`, borderRadius: designTokens.radii.badge, paddingBlock: {badge_padding_y}, paddingInline: {badge_padding_x}, fontSize: {badge_font_size}, fontWeight: {badge_font_weight} }},
  neutral: {{ background: designTokens.colors.secondarySurface, color: designTokens.colors.primaryText, border: `${{designTokens.borders.labelWidth}} solid ${{designTokens.colors.border}}`, borderRadius: designTokens.radii.badge, paddingBlock: {badge_padding_y}, paddingInline: {badge_padding_x}, fontSize: {badge_font_size}, fontWeight: {badge_font_weight} }},
  success: {{ background: designTokens.colors.successSoft, color: designTokens.colors.success, border: `${{designTokens.borders.labelWidth}} solid ${{designTokens.colors.border}}`, borderRadius: designTokens.radii.badge, paddingBlock: {badge_padding_y}, paddingInline: {badge_padding_x}, fontSize: {badge_font_size}, fontWeight: {badge_font_weight} }},
  warning: {{ background: designTokens.colors.warningSoft, color: designTokens.colors.warning, border: `${{designTokens.borders.labelWidth}} solid ${{designTokens.colors.border}}`, borderRadius: designTokens.radii.badge, paddingBlock: {badge_padding_y}, paddingInline: {badge_padding_x}, fontSize: {badge_font_size}, fontWeight: {badge_font_weight} }},
  danger: {{ background: designTokens.colors.dangerSoft, color: designTokens.colors.dangerText, border: `${{designTokens.borders.labelWidth}} solid ${{designTokens.colors.border}}`, borderRadius: designTokens.radii.badge, paddingBlock: {badge_padding_y}, paddingInline: {badge_padding_x}, fontSize: {badge_font_size}, fontWeight: {badge_font_weight} }},
}};

export const cardRecipe = {{
  default: {{
    background: "{escape_ts(card_surface)}",
    border: "{escape_ts(card_border_style)}",
    borderRadius: designTokens.radii.card,
    boxShadow: "{escape_ts(card_shadow)}",
    padding: {card_padding},
  }},
  resource: {{
    background: "{escape_ts(card_surface)}",
    border: `${{designTokens.borders.boxWidth}} solid ${{designTokens.colors.headerBorder}}`,
    borderRadius: designTokens.radii.card,
    padding: {card_padding},
  }},
}} as const;

export const tableRecipe = {{
  header: {{
    background: "{escape_ts(table_header_bg)}",
    color: designTokens.colors.secondaryText,
    fontSize: {table_header_size},
  }},
  row: {{
    borderBottom: "{escape_ts(table_row_border_style)}",
    hoverBackground: "{escape_ts(table_row_hover_bg)}",
  }},
  cell: {{
    paddingBlock: {table_cell_padding_y},
    paddingInline: {table_cell_padding_x},
  }},
}} as const;

export const overlayRecipe = {{
  modal: {{
    background: designTokens.colors.surface,
    border: `${{designTokens.borders.boxWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: {int_value(modal_component.get("radius"), box_radius)},
    boxShadow: designTokens.shadows.modal ?? "none",
    maxWidth: {modal_width},
  }},
  drawer: {{
    background: designTokens.colors.surface,
    boxShadow: designTokens.shadows.drawer ?? "none",
    anchor: "{escape_ts(str_value(drawer_component.get("anchor"), "right"))}",
  }},
  toast: {{
    background: designTokens.colors.surface,
    border: `${{designTokens.borders.boxWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: {int_value(toast_component.get("radius"), box_radius)},
    boxShadow: designTokens.shadows.popover ?? "none",
    paddingBlock: {toast_padding_y},
    paddingInline: {toast_padding_x},
  }},
}} as const;

export const appShellRecipe = {{
  sidebarWidth: {int_value(app_shell_component.get("sidebarWidth"), 240)},
  topNavHeight: {int_value(app_shell_component.get("topNavHeight"), 64)},
  sidebarBackground: "{escape_ts(sidebar_bg)}",
  mainBackground: "{escape_ts(main_bg)}",
  activeNavBackground: "{escape_ts(active_nav_bg)}",
  activeNavText: "{escape_ts(active_nav_text)}",
}} as const;

export const componentRecipe = {{
  page: {{
    background: designTokens.colors.page,
    color: designTokens.colors.primaryText,
    fontFamily: designTokens.typography.fontFamily,
  }},
  card: {{
    ...cardRecipe.default,
  }},
  input: {{
    ...inputRecipe.default,
  }},
  header: {{
    background: designTokens.colors.header,
    color: designTokens.colors.primaryText,
    borderBottom: `1px solid ${{designTokens.colors.headerBorder}}`,
  }},
  footer: {{
    background: designTokens.colors.footer,
    color: designTokens.colors.secondaryText,
  }},
  badge: {{
    ...badgeRecipe,
  }},
}} as const;
"""


def css_width(scale: str) -> str:
    raw = BORDER_WIDTHS[scale]
    return "0" if raw == "0" else f"{raw}px"


def css_number_width(value: int | float | str) -> str:
    if isinstance(value, (int, float)):
        return "0" if value == 0 else f"{value:g}px"
    return value


def points_width(value: str) -> str:
    return value.removesuffix("px") if value.endswith("px") else value


def dp_width(value: str) -> str:
    raw = points_width(value)
    return f"{raw}.dp"


def escape_swift(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def escape_kotlin(value: str) -> str:
    return escape_swift(value)


def escape_ts(value: str) -> str:
    return escape_swift(value)


def write_file(path: Path, content: str, check: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized = content.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != normalized:
            print(f"DIFF {path}")
            for line in difflib.unified_diff(
                current.splitlines(),
                normalized.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ):
                print(line)
            return False
        return True
    path.write_text(normalized)
    return True


def generate(
    project_root: Path,
    platform: str,
    theme_slug: str,
    package_name: str,
    check: bool,
    output: Path | None = None,
) -> bool:
    tokens = read_theme(theme_slug)
    project_root = project_root.resolve()

    outputs = {
        "swift": (project_root / "styling.gen.swift", swift(tokens)),
        "kotlin": (project_root / "styling.gen.kt", kotlin(tokens, package_name)),
        "typescript": (project_root / "styling.gen.ts", typescript(tokens)),
    }

    path, content = outputs[platform]
    if output is not None:
        path = output if output.is_absolute() else project_root / output
    return write_file(path, content, check)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_root", nargs="?", default=".", help="Project root to receive generated files.")
    parser.add_argument(
        "--platform",
        required=True,
        choices=("swift", "kotlin", "typescript"),
        help="Platform styling file to generate.",
    )
    parser.add_argument(
        "--theme",
        default="light",
        help="Theme JSON under themes/ to use, without the .json suffix. Defaults to light.",
    )
    parser.add_argument(
        "--kotlin-package",
        default="com.designarchitect.designsystem",
        help="Package name for styling.gen.kt.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Print diffs and fail if generated files are stale.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional generated-file path, relative to project root unless absolute.",
    )
    args = parser.parse_args()

    try:
        ok = generate(
            Path(args.project_root),
            args.platform,
            args.theme,
            args.kotlin_package,
            args.check,
            args.output,
        )
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check and not ok:
        return 1

    verb = "Checked" if args.check else "Generated"
    print(f"{verb} {args.platform} design system for theme '{args.theme}' in {Path(args.project_root).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
