#!/usr/bin/env python3
"""Generate design spec metadata for the example app."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESIGNS_DIR = ROOT / "designs"
OUTPUT = ROOT / "example" / "src" / "generated" / "designs.gen.ts"


def parse_frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text().splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path} is missing YAML frontmatter.")

    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip("\"'")
    return fields


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--designs-dir",
        type=Path,
        default=DESIGNS_DIR,
        help=f"Directory containing design spec Markdown files. Defaults to {DESIGNS_DIR}.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help=f"Generated TypeScript metadata file. Defaults to {OUTPUT}.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Print diffs and fail if generated example design metadata is stale.",
    )
    return parser.parse_args()


def render_design_options(designs_dir: Path) -> tuple[str, int]:
    if not designs_dir.is_dir():
        raise ValueError(f"{designs_dir} is missing.")

    rows: list[dict[str, str]] = []
    for spec_path in sorted(designs_dir.glob("*.md")):
        if spec_path.name == "TEMPLATE.md":
            continue
        fields = parse_frontmatter(spec_path)
        missing = [field for field in ("name", "description") if not fields.get(field)]
        if missing:
            raise ValueError(f"{spec_path} frontmatter is missing: {', '.join(missing)}.")
        rows.append(
            {
                "id": spec_path.stem,
                "name": fields["name"],
                "description": fields["description"],
                "path": f"designs/{spec_path.name}",
            }
        )

    entries = ",\n".join(
        "  { "
        + f'id: "{row["id"]}", '
        + f'name: "{escape(row["name"])}", '
        + f'description: "{escape(row["description"])}", '
        + f'path: "{row["path"]}"'
        + " }"
        for row in rows
    )
    return (
        "// Generated by design-architect. Do not edit manually.\n\n"
        f"export const designOptions = [\n{entries}\n] as const;\n",
        len(rows),
    )


def write_file(path: Path, content: str, check: bool) -> bool:
    normalized = content.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != normalized:
            print(f"DIFF {path}")
            for line in difflib.unified_diff(
                current.splitlines(),
                normalized.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ):
                print(line)
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized)
    return True


def main() -> int:
    args = parse_args()
    try:
        content, count = render_design_options(args.designs_dir)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    ok = write_file(args.output, content, args.check)
    if args.check and not ok:
        return 1

    verb = "Checked" if args.check else "Generated"
    print(f"{verb} {count} example design specs in {args.output}")
    return 0


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
