#!/usr/bin/env python3
"""Generate TypeScript theme modules for the example app."""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
THEMES_DIR = ROOT / "themes"
GENERATOR = ROOT / "scripts" / "generate_components.py"
OUTPUT_DIR = ROOT / "example" / "src" / "generated" / "themes"


def theme_slugs() -> list[str]:
    return sorted(path.stem for path in THEMES_DIR.glob("*.json") if path.name != "theme.schema.json")


def theme_context(slugs: list[str]) -> str:
    default_theme = "light" if "light" in slugs else slugs[0]
    imports = "\n".join(
        f'import * as theme_{slug.replace("-", "_")} from "./{slug}.gen";' for slug in slugs
    )
    entries = "\n".join(
        f'  "{slug}": theme_{slug.replace("-", "_")},' for slug in slugs
    )
    return f'''// Generated by design-architect. Do not edit manually.

import {{
  createContext,
  type CSSProperties,
  type ReactNode,
  useContext,
  useMemo,
  useState,
}} from "react";
{imports}

export const themes = {{
{entries}
}} as const;

export type ThemeId = keyof typeof themes;
export type ThemeModule = (typeof themes)[ThemeId];

type ThemeContextValue = {{
  themeId: ThemeId;
  theme: ThemeModule;
  setThemeId: (themeId: ThemeId) => void;
  themeOptions: Array<{{
    id: ThemeId;
    name: string;
    description: string;
  }}>;
  cssVariables: CSSProperties;
}};

const ThemeContext = createContext<ThemeContextValue | null>(null);

export function ThemeProvider({{ children }}: {{ children: ReactNode }}) {{
  const [themeId, setThemeId] = useState<ThemeId>("{default_theme}");
  const theme = themes[themeId];

  const themeOptions = useMemo(
    () =>
      (Object.keys(themes) as ThemeId[]).map((id) => ({{
        id,
        name: themes[id].designTheme.name,
        description: themes[id].designTheme.description,
      }})),
    [],
  );

  const cssVariables = useMemo(
    () =>
      ({{
        "--page": theme.designTokens.colors.page,
        "--surface": theme.designTokens.colors.surface,
        "--secondary-surface": theme.designTokens.colors.secondarySurface,
        "--header": theme.designTokens.colors.header,
        "--header-border": theme.designTokens.colors.headerBorder,
        "--footer": theme.designTokens.colors.footer,
        "--primary-text": theme.designTokens.colors.primaryText,
        "--secondary-text": theme.designTokens.colors.secondaryText,
        "--placeholder-text": theme.designTokens.colors.placeholderText,
        "--border": theme.designTokens.colors.border,
        "--focus-ring": theme.designTokens.colors.focusRing,
        "--brand": theme.designTokens.colors.brand,
        "--hover": theme.designTokens.colors.hover,
        "--font-family": theme.designTokens.typography.fontFamily,
        "--motion-hover": theme.designTokens.motion.hover,
      }}) as CSSProperties,
    [theme],
  );

  return (
    <ThemeContext.Provider
      value={{{{ themeId, theme, setThemeId, themeOptions, cssVariables }}}}
    >
      {{children}}
    </ThemeContext.Provider>
  );
}}

export function useTheme() {{
  const value = useContext(ThemeContext);
  if (!value) {{
    throw new Error("useTheme must be used within ThemeProvider");
  }}
  return value;
}}
'''


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    generated_files: set[Path] = set()
    slugs = theme_slugs()

    for slug in slugs:
        with tempfile.TemporaryDirectory(prefix=f"design-architect-{slug}-") as temp_dir:
            subprocess.run(
                [
                    "python3",
                    str(GENERATOR),
                    temp_dir,
                    "--platform",
                    "typescript",
                    "--theme",
                    slug,
                ],
                check=True,
            )
            destination = OUTPUT_DIR / f"{slug}.gen.ts"
            shutil.copyfile(Path(temp_dir) / "styling.gen.ts", destination)
            generated_files.add(destination)

    for path in OUTPUT_DIR.glob("*.gen.ts"):
        if path not in generated_files:
            path.unlink()

    (OUTPUT_DIR / "ThemeContext.tsx").write_text(theme_context(slugs), encoding="utf-8")

    print(f"Generated {len(generated_files)} example theme modules in {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
