#!/usr/bin/env python3
"""Generate design spec metadata for the example app."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESIGNS_DIR = ROOT / "designs"
OUTPUT = ROOT / "example" / "src" / "generated" / "designs.gen.ts"


def parse_frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text().splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path} is missing YAML frontmatter.")

    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip("\"'")
    return fields


def main() -> int:
    rows: list[dict[str, str]] = []
    for spec_path in sorted(DESIGNS_DIR.glob("*.md")):
        if spec_path.name == "TEMPLATE.md":
            continue
        fields = parse_frontmatter(spec_path)
        rows.append(
            {
                "id": spec_path.stem,
                "name": fields["name"],
                "description": fields["description"],
                "path": f"designs/{spec_path.name}",
            }
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    entries = ",\n".join(
        "  { "
        + f'id: "{row["id"]}", '
        + f'name: "{escape(row["name"])}", '
        + f'description: "{escape(row["description"])}", '
        + f'path: "{row["path"]}"'
        + " }"
        for row in rows
    )
    OUTPUT.write_text(
        "// Generated by design-architect. Do not edit manually.\n\n"
        f"export const designOptions = [\n{entries}\n] as const;\n"
    )
    print(f"Generated {len(rows)} example design specs in {OUTPUT}")
    return 0


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
